spring:
    application:
        name: checkout-service
    cloud:
        stream:
            default.contentType: application/json
            bindings:
                stockChannel.destination: stock
                stockChannel.group: checkout
            kafka:
                bindings.input.customer.autoCommitOffset: false
                binder:
                    brokers : localhost:9092
                    zkNodes: localhost

server:
    port: 8083

checkout:
    api.url: http://localhost:8080/api/checkout

eureka:
    client:
        service-url:
            defaultZone: http://${DISCOVERY:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true

feign:
    hystrix:
        enabled: true

