spring:
  application:
    name: store-service
  cloud:
    stream:
      default.contentType: application/json
      bindings:
        stockChannel.destination: stock
        stockChannel.group: store
      kafka:
        bindings.input.customer.autoCommitOffset: false
        binder:
          brokers : ${KAFKA:localhost}
          zkNodes: ${ZOOKEEPER:localhost}
    
server:
  port: 8081
  
inventory:
  api.url: http://localhost:8080/api/inventory

inventory-service:
  ribbon:
    eureka:
      enable	: true
    MaxAutoRetries : 3
    MaxAutoRetriesNextServer : 3

eureka: 
  client:
    service-url:
      defaultZone: http://${DISCOVERY:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true

hystrix.commmand.default.execution.isolation.strategy: SEMAPHORE

feign:
  oauth2:
    enabled: true
  hystrix:
    enabled: true


